### ISSUE TITLE
Fresh install failing with missing --token option

### ISSUE THREAD

**Issue by skoczen** [boxen/our-boxen#395]
Hey team,

Fresh clone/install of boxen and boxen-web as of today.  Installing onto a fresh mac, 10.8.3, straight out of the box.

When running the install script, I get:
```bash
curl -s https://our_org.herokuapp.com/script/e13ba2f9.sh > /tmp/install-boxen; bash /tmp/install-boxen
 
    ########   #######  ##     ## ######## ##    ##
    ##     ## ##     ##  ##   ##  ##       ###   ##
    ##     ## ##     ##   ## ##   ##       ####  ##
    ########  ##     ##    ###    ######   ## ## ##
    ##     ## ##     ##   ## ##   ##       ##  ####
    ##     ## ##     ##  ##   ##  ##       ##   ###
    ########   #######  ##     ## ######## ##    ##
    OUR_ORG
 
    Hello! I'm going to set up this machine for you. It might take me a bit
    of time before I'm done, but you'll end up with a happy machine by the
    end of it.
 
    Ready to get started? Brutalize a key with your favorite finger.
 
--> For added privacy invasion I'll need your local account's password.
    Password for sudo: 
    Sweet, thanks. I'll see you in Vegas, sucker.
 
--> Making sure /opt/boxen exists and belongs to you.
 
--> Configuring. Prepare for a long wait and some weird output.
    I might have to ask you for your password again too.
/opt/boxen/repo/.bundle/ruby/1.8/gems/boxen-1.5.2/lib/boxen/flags.rb:227:in `parse': invalid option: --token (Boxen::Error)
Usage: boxen [options] [projects...]
 
        --debug                      Be really verbose.
        --pretend, --noop            Don't make changes.
        --report                     Enable puppet reports.
        --env                        Show useful environment variables.
    -h, -?, --help                   Show help.
        --disable-service SERVICE    Disable a Boxen service.
        --enable-service SERVICE     Enable a Boxen service.
        --restart-service SERVICE    Restart a Boxen service.
        --disable-services           Disable all Boxen services.
        --enable-services            Enable all Boxen services.
        --restart-services           Restart all Boxen services.
        --list-services              List Boxen services.
        --homedir DIR                Boxen's home directory.
        --logfile DIR                Boxen's log file.
        --login LOGIN                Your GitHub login.
        --no-fde                     Don't require full disk encryption.
        --no-pull                    Don't try to update code before applying.
        --no-issue, --stealth        Don't open an issue on failure.
        --password PASSWORD          Your GitHub password.
        --profile                    Profile the Puppet run.
        --future-parser              Enable the Puppet future parser
        --projects                   Show available projects.
        --srcdir DIR                 The directory where repos live.
        --user USER                  Your local user.
        --no-color                   Disable colors.
from /opt/boxen/repo/.bundle/ruby/1.8/gems/boxen-1.5.2/lib/boxen/flags.rb:150:in `initialize'
from /opt/boxen/repo/.bundle/ruby/1.8/gems/boxen-1.5.2/lib/boxen/cli.rb:35:in `new'
from /opt/boxen/repo/.bundle/ruby/1.8/gems/boxen-1.5.2/lib/boxen/cli.rb:35:in `run'
from script/boxen:79
```

Any ideas?

**Comment by seanknox** [comment]
@skoczen Believe this issue is fixed. Can you close this?

**Comment by skoczen** [comment]
Happy to close, but can't tell you if it's fixed - didn't decide to go with boxen at my new company, so have no installs handy!
