### ISSUE TITLE
Trying to install module but getting "tar: Unrecognized archive format"

### ISSUE THREAD

**Issue by joshuairl** [boxen/our-boxen#412]
This is my repo I'm trying to add in.
https://github.com/joshuairl/puppet-hosts_prefpane

I had it doing more and was getting:
Error: /Stage[main]/Hosts_prefpane/Package[HostsPrefPane]: Provider pkg is not functional on this host

But upped the version number and now I'm getting that top error.

I've tried clearing .librarian, .tmp, and Puppetfile.lock and it stills occurs...?
```
mccme-rountrjf:boxen joshua$ boxen --no-fde
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/fileutils.rb:1414:in `fu_each_src_dest0': undefined method `to_str' for nil:NilClass (NoMethodError)
	from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/fileutils.rb:1400:in `fu_each_src_dest'
	from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/fileutils.rb:423:in `cp_r'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-puppet-0.9.10/lib/librarian/puppet/source/githubtarball.rb:60:in `install_version!'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-puppet-0.9.10/lib/librarian/puppet/source/githubtarball.rb:218:in `install!'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-puppet-0.9.10/vendor/librarian/lib/librarian/manifest.rb:191:in `install!'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-puppet-0.9.10/vendor/librarian/lib/librarian/action/install.rb:49:in `install_manifests'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-puppet-0.9.10/vendor/librarian/lib/librarian/action/install.rb:48:in `each'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-puppet-0.9.10/vendor/librarian/lib/librarian/action/install.rb:48:in `install_manifests'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-puppet-0.9.10/vendor/librarian/lib/librarian/action/install.rb:39:in `perform_installation'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-puppet-0.9.10/vendor/librarian/lib/librarian/action/install.rb:12:in `run'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-puppet-0.9.10/vendor/librarian/lib/librarian/cli.rb:157:in `install!'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-puppet-0.9.10/lib/librarian/puppet/cli.rb:64:in `install'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/thor-0.18.1/lib/thor/command.rb:27:in `__send__'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-puppet-0.9.10/vendor/librarian/lib/librarian/cli.rb:29:in `bin!'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-puppet-0.9.10/bin/librarian-puppet:9
	from /opt/boxen/repo/bin/librarian-puppet:16:in `load'
	from /opt/boxen/repo/bin/librarian-puppet:16
Can't run Puppet, fetching dependencies with librarian failed.
```

**Comment by seanknox** [comment]
@joshuairl is this still an issue or can it be closed?

**Comment by seanknox** [comment]
Closing this since been a while since it was original reported. If it's still happening feel free to reopen.
