### ISSUE TITLE
Bundler::GemNotFound

### ISSUE THREAD

**Issue by nomasprime** [boxen/our-boxen#438]
Recently updated to Mavericks, when I run boxen I get several errors from bundler saying gem not found:

```
/Library/Ruby/Gems/2.0.0/gems/bundler-1.3.5/lib/bundler/spec_set.rb:92:in `materialize': Could not find addressable-2.3.5 in any of the sources (Bundler::GemNotFound)
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.3.5/lib/bundler/spec_set.rb:85:in `map!'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.3.5/lib/bundler/spec_set.rb:85:in `materialize'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.3.5/lib/bundler/definition.rb:114:in `specs'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.3.5/lib/bundler/definition.rb:159:in `specs_for'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.3.5/lib/bundler/definition.rb:148:in `requested_specs'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.3.5/lib/bundler/environment.rb:18:in `requested_specs'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runtime.rb:13:in `setup'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.3.5/lib/bundler.rb:120:in `setup'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.3.5/lib/bundler/setup.rb:17
Error: Could not set 'present' on ensure: undefined method `strip' for nil:NilClass at 2:/opt/boxen/repo/shared/libtool/manifests/init.pp
Error: Could not set 'present' on ensure: undefined method `strip' for nil:NilClass at 2:/opt/boxen/repo/shared/libtool/manifests/init.pp
Wrapped exception:
undefined method `strip' for nil:NilClass
Error: /Stage[main]/Libtool/Package[libtool]/ensure: change from absent to present failed: Could not set 'present' on ensure: undefined method `strip' for nil:NilClass at 2:/opt/boxen/repo/shared/libtool/manifests/init.pp
```

Been trying to get it working for hours, need help.

**Comment by Nancy-zj** [comment]
：(
