### ISSUE TITLE
encode error on install

### ISSUE THREAD

**Issue by drewrothstein** [boxen/our-boxen#755]
Attempting to install boxen on OS X 10.10.3.

After accepting my GitHub OTP, it fails out with-
```
/opt/boxen/repo/.bundle/ruby/2.0.0/gems/json-1.8.2/lib/json/common.rb:223:in `encode': "\xE2" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/json-1.8.2/lib/json/common.rb:223:in `generate'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/json-1.8.2/lib/json/common.rb:223:in `generate'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/json-1.8.2/lib/json/common.rb:394:in `dump'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/sawyer-0.5.5/lib/sawyer/serializer.rb:49:in `call'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/sawyer-0.5.5/lib/sawyer/serializer.rb:49:in `encode'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/sawyer-0.5.5/lib/sawyer/agent.rb:116:in `encode_body'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/sawyer-0.5.5/lib/sawyer/agent.rb:96:in `block in call'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:374:in `block in run_request'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:388:in `block in build_request'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/faraday-0.9.1/lib/faraday/request.rb:26:in `block in create'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/faraday-0.9.1/lib/faraday/request.rb:25:in `tap'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/faraday-0.9.1/lib/faraday/request.rb:25:in `create'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:384:in `build_request'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:370:in `run_request'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `post'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/sawyer-0.5.5/lib/sawyer/agent.rb:94:in `call'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/octokit-2.7.2/lib/octokit/client.rb:257:in `request'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/octokit-2.7.2/lib/octokit/client.rb:138:in `post'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/octokit-2.7.2/lib/octokit/client/authorizations.rb:70:in `create_authorization'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/boxen-2.7.2/lib/boxen/preflight/creds.rb:88:in `run'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/boxen-2.7.2/lib/boxen/check.rb:28:in `block in run'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/boxen-2.7.2/lib/boxen/check.rb:28:in `each'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/boxen-2.7.2/lib/boxen/check.rb:28:in `run'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/boxen-2.7.2/lib/boxen/cli.rb:43:in `run'
	from ./script/boxen:165:in `<main>'
```

All that has been done up to this point is that it has asked for my GitHub credentials-
```
[Cm-Fm7-B♭sus-C5 repo (master)]$ ./script/boxen
--> Preparing to auto-update...
--> Complete! Nothing new from upstream.
GitHub login: |drothstein| drewrothstein
GitHub password: **************************************************

--> It looks like you have two-factor auth enabled.

One time password (via SMS or device):
******
```

Checked out a couple SHAs back, `1de9c88bcf6b96d05e12722b35a997591ff3ce2f` and it was able to run successfully.  Then I was able to checkout master and it kept working.

Happy to provide more system information if helpful.

**Comment by jacobbednarz** [comment]
Hi @drewrothstein! Thanks for opening an issue, unfortunately it's been a while and it hasn't been updated. Could you please let me know if this is still an issue? I'm going to close this off but if you reply I'll gladly open it back up and help you work through the problem.
