### ISSUE TITLE
Running brew

### ISSUE THREAD

**Issue by ki0** [boxen/our-boxen#865]
Hi there,

I dont know what it is happening but from some time i got this answer from boxen:

```
➜  brew upgrade
Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/gcc5.rb:67:in `<class:Gcc5>'
Please report this to the boxen/brews tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/gcc5.rb:67:in `<class:Gcc5>'
Please report this to the boxen/brews tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/gcc5.rb:67:in `<class:Gcc5>'
Please report this to the boxen/brews tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/gcc5.rb:67:in `<class:Gcc5>'
Please report this to the boxen/brews tap!

Error: Calling BottleSpecification.revision is disabled!
Use BottleSpecification.rebuild instead.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/git.rb:10:in `block in <class:Git>'
Please report this to the boxen/brews tap!
Or, even better, submit a PR to fix it!
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  boxen/brews
```

What can i do? it seems it is outdated.
Cheers.

**Comment by jacobbednarz** [comment]
The error message you're receiving is due to the vendored Homebrew formula using deprecated directives. 

- GCC: the `fails_with` directive was removed in boxen/puppet-gcc#21 so best to upgrade to the latest version of that if you still need it.
- Git: I've never seen that error message. Would you be able to open an issue at [`boxen/puppet-git`](https://github.com/boxen/puppet-git) with some more in depth details like versions used, formula contents, etc and we'll take a look there?
